name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened, labeled]
  workflow_dispatch:
    inputs:
      run-extended:
        description: 'Run extended test suite'
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          python tests/test_vector_ops.py
          
      - name: Comment on issue if tests fail
        if: failure() && github.event_name == 'issues'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Tests are failing! Claude Code should investigate this issue.'
            })
    
    extended-tests:
      runs-on: ubuntu-latest
      if: |
        github.event_name == 'workflow_dispatch' && github.event.inputs.run-extended == 'true' ||
        contains(github.event.head_commit.message, '[extended]') ||
        contains(github.event.pull_request.labels.*.name, 'extended-tests')
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
            
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
        - name: Run extended tests
          run: |
            python tests/extended_tests.py
            
        - name: Comment on issue if tests fail
          if: failure() && github.event_name == 'issues'
          uses: actions/github-script@v6
          with:
            script: |
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '❌ Tests are failing! Claude Code should investigate this issue.'
              })
